### ISSUE TITLE
无法实现部件检索的完整功能，而Android版没问题

### ISSUE THREAD

**Issue by ConcealedBlade** [Jimex/DintTango-Windows#4]
https://forum.freemdict.com/t/topic/10387

点击每个字不同的四个角，会触发不同的功能：
左上角——取代搜索框汉字
右上角——跳转叶典
左下角——在上方存储汉字
右下角——搜索异体字

![image](https://github.com/Jimex/DintTango-Windows/assets/63355926/461a7518-5c05-400c-91e9-a07e58d0c064)

**Comment by Jimex** [comment]
建议你看看控制台有什么错误提示

**Comment by ConcealedBlade** [comment]
没看到错误提示

**Comment by Jimex** [comment]
经测试在我电脑上正常

**Comment by ConcealedBlade** [comment]
正常运行是可以，就是实现不了这四角功能，只能实现左下角和右下角功能，别的像是没正常触发。

看看Android录屏

https://github.com/Jimex/DintTango-Windows/assets/63355926/e7c38378-71fd-4ad0-aa21-e073c62283b6

**Comment by Jimex** [comment]
我电脑上正常，暂时无法重现这个错误

https://github.com/Jimex/DintTango-Windows/assets/3145858/e9d3c796-654e-4af1-9be5-9f6bc8b4eb69

**Comment by ConcealedBlade** [comment]
此问题已经在删除用户数据重新安装DictTango后得到彻底解决。
