### ISSUE TITLE
a href大小写敏感

### ISSUE THREAD

**Issue by ConcealedBlade** [Jimex/DintTango-Windows#7]
![image](https://github.com/Jimex/DintTango-Windows/assets/63355926/6c39331f-02e5-4988-967d-59be49b8762a)
![image](https://github.com/Jimex/DintTango-Windows/assets/63355926/be2c25b3-8d97-4c63-acc5-b5de3ce374bc)
![image](https://github.com/Jimex/DintTango-Windows/assets/63355926/b48af212-9180-430a-a95e-d300ecb33a5a)

**Comment by Jimex** [comment]
请提供一下测试mdx

**Comment by ConcealedBlade** [comment]
再提供一个很简单的
![image](https://github.com/Jimex/DintTango-Windows/assets/63355926/7fc22adc-8c69-473a-bfa3-df220dff0f69)
![image](https://github.com/Jimex/DintTango-Windows/assets/63355926/81e3461e-c57a-4d58-affd-74de09562637)

[test.zip](https://github.com/Jimex/DintTango-Windows/files/15025008/test.zip)

**Comment by Jimex** [comment]
这个错误发生在使用阅读模式打开过词典后，下版本会修正这个问题。
