### ISSUE TITLE
在a href中出现双引号没有进行转义

### ISSUE THREAD

**Issue by ConcealedBlade** [Jimex/DintTango-Windows#9]
![image](https://github.com/Jimex/DintTango-Windows/assets/63355926/6ec5622d-3d33-4741-9bdb-8694dc66fd4a)

测试mdx搜索sounds

[Ask the Editor.zip](https://github.com/Jimex/DintTango-Windows/files/15152723/Ask.the.Editor.zip)

**Comment by ConcealedBlade** [comment]
Android版本具有相同问题，难道需要提前对特殊符号进行转义？

**Comment by Jimex** [comment]
对于Href中的双引号，肯定要提前在词典中转换的，不然已经破坏了html的结构了

**Comment by ConcealedBlade** [comment]
别的符号都可以保持原样吗？因为之前听你说不用进行转义。

**Comment by Jimex** [comment]
双引号是字符串的边界符，肯定要转换的，不然应用程序怎么知道哪里是href的开头和结尾
